export const serviceCategories = [
  {
    id: "city-tours",
    title: "Curated Tour Packages",
    description:
      "Immersive cultural experiences, guided by locals who know every hidden gem.",
    image: "/assets/hero/city-tours.jpg",
    href: "/city-tours",
    metrics: "200+ itineraries",
  },
  {
    id: "car-rental",
    title: "Luxury Car Rental",
    description:
      "Premium vehicles with professional chauffeurs for business, leisure, or events.",
    image: "/assets/hero/car-rental.jpg",
    href: "/car-rental",
    metrics: "50+ premium models",
  },
  {
    id: "airport-transport",
    title: "Airport Transfers",
    description:
      "Seamless arrivals and departures with real-time monitoring and meet & greet.",
    image: "/assets/hero/airport-transport.jpg",
    href: "/airport-transport",
    metrics: "24/7 availability",
  },
  {
    id: "hotel-booking",
    title: "Hotel Booking",
    description:
      "Premium accommodations with exclusive rates, concierge services, and flexible cancellation.",
    image: "/assets/hero/hotel-booking.jpg",
    href: "/hotel-booking",
    metrics: "100+ properties",
  },
];

export const featuredPackages = [
  {
    id: "venice-romance",
    title: "Romantic Venice Escape",
    destination: "Italy",
    duration: "5 Days",
    price: 2299,
    rating: 4.9,
    highlights: ["Private Gondola Ride", "Michelin-Star Dining", "Luxury Suite"],
    image: "/assets/categories/city-tours/muscat-daymaniat-islands-snorkeling-lunch/1.avif",
  },
  {
    id: "tokyo-discovery",
    title: "Tokyo Discovery",
    destination: "Japan",
    duration: "7 Days",
    price: 2899,
    rating: 4.8,
    highlights: ["Personal Guide", "Sushi Masterclass", "Mt. Fuji Day Trip"],
    image: "/assets/categories/car-rental/muscat-private-transfer-to-dubai/1.webp",
  },
  {
    id: "bali-retreat",
    title: "Bali Wellness Retreat",
    destination: "Indonesia",
    duration: "6 Days",
    price: 1899,
    rating: 4.7,
    highlights: ["Oceanfront Villa", "Daily Spa Rituals", "Sunrise Yoga"],
    image: "/assets/categories/airport-transport/muscat-airport-all-city-hotels-private-transfers/1.avif",
  },
];

export const testimonials = [
  {
    name: "Amelia Carter",
    role: "Luxury Travel Blogger",
    quote:
      "citymuscattours crafted the most thoughtful itinerary I've ever experienced. Every detail exceeded expectations.",
    image:
      "https://images.unsplash.com/photo-1544723795-3fb6469f5b39?w=300&h=300&fit=crop",
  },
  {
    name: "Rahul Verma",
    role: "Founder, Verma Group",
    quote:
      "Our corporate retreat was flawless. The team curated unique activities that kept our executives energized.",
    image:
      "https://images.unsplash.com/photo-1531891437562-4301cf35b7e4?w=300&h=300&fit=crop",
  },
  {
    name: "Sofia Mendes",
    role: "Creative Director",
    quote:
      "From airport pickup to bespoke tour packages, the service felt personal and premium. Highly recommended!",
    image:
      "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=300&h=300&fit=crop",
  },
];

export const faqs = [
  {
    question: "Can I customize an itinerary?",
    answer:
      "Absolutely. Our travel specialists work with you to tailor each experience to your preferences, from activities to accommodations.",
  },
  {
    question: "Do you offer group discounts?",
    answer:
      "We provide tailored pricing for groups of 6 or more travelers. Contact our concierge team for a personalized quote.",
  },
  {
    question: "Which payment methods do you accept?",
    answer:
      "We support all major credit cards, Razorpay, and Stripe. Secure payments and deposits are handled through verified gateways.",
  },
  {
    question: "How are cancellations handled?",
    answer:
      "Cancellation policies vary by package. We outline terms during booking and offer flexible options when possible.",
  },
];

export const stats = [
  { id: "travelers", label: "Travelers served", value: "18k+" },
  { id: "destinations", label: "Global destinations", value: "120" },
  { id: "partners", label: "Premium partners", value: "85" },
  { id: "satisfaction", label: "Satisfaction rate", value: "98%" },
];

export const categoryDetails = {
  "city-tours": {
    title: "Tour Packages",
    subtitle: "Chic urban storytelling",
    description:
      "Discover iconic architecture, hidden alleys, and Michelin-starred dining with our expert local guides.",
    heroImage: "/assets/hero/city-tours.jpg",
  },
  "car-rental": {
    title: "Car Rental",
    subtitle: "Signature rides & chauffeurs",
    description:
      "Arrive in style with luxury vehicles, curated amenities, and chauffeurs trained in hospitality.",
    heroImage: "/assets/hero/car-rental.jpg",
  },
  "airport-transport": {
    title: "Airport Transport",
    subtitle: "Seamless arrivals & departures",
    description:
      "Experience smooth transitions with flight monitoring, dedicated hosts, and 24/7 support.",
    heroImage: "/assets/hero/airport-transport.jpg",
  },
  "hotel-booking": {
    title: "Hotel Booking",
    subtitle: "Premium accommodations",
    description:
      "Discover luxury hotels and resorts with exclusive rates, personalized service, and flexible booking options.",
    heroImage: "/assets/hero/hotel-booking.jpg",
  },
};

type CategoryPackageRecord = {
  id: string;
  title: string;
  description: string;
  duration: string;
  price: number;
  image: string;
  perks: string[];
  rating: number;
  currency?: string;
  badge?: string;
  reviews?: number;
  oldPrice?: number;
  location?: string;
  highlights?: string[];
  included?: string[];
  excluded?: string[];
  essentials?: string[];
  overview?: string;
  meetingPoint?: string;
  gallery?: string[];
  languages?: string[];
  availability?: string;
  mobileTicket?: string;
  pickupIncluded?: boolean;
  ageRestriction?: string;
};

export const categoryPackages: Record<
  keyof typeof categoryDetails,
  CategoryPackageRecord[]
> = {
  "city-tours": [
    {
      id: "muscat-daymaniat-islands-snorkeling-lunch",
      title: "Muscat: Daymaniat Islands Snorkeling Trip with Lunch",
      description: "Explore the pristine Daymaniat Islands with snorkeling and a delicious lunch included.",
      duration: "4.5 hours",
      price: 6855,
      oldPrice: 9264,
      currency: "INR",
      image: "/assets/categories/city-tours/muscat-daymaniat-islands-snorkeling-lunch/1.avif",
      gallery: [
        "/assets/categories/city-tours/muscat-daymaniat-islands-snorkeling-lunch/2.avif",
        "/assets/categories/city-tours/muscat-daymaniat-islands-snorkeling-lunch/3.avif",
        "/assets/categories/city-tours/muscat-daymaniat-islands-snorkeling-lunch/4.avif",
      ],
      perks: ["Snorkeling equipment", "Lunch included", "Professional guide"],
      highlights: [
        "Snorkel in crystal-clear waters around Daymaniat Islands",
        "Enjoy a delicious lunch on board",
        "Spot colorful marine life and coral reefs",
      ],
      included: ["Snorkeling equipment", "Lunch", "Professional guide", "Boat transfer"],
      essentials: ["Bring swimwear and towel", "Sunscreen recommended", "Waterproof camera optional"],
      overview: "Discover the underwater beauty of Daymaniat Islands with a guided snorkeling trip and lunch.",
      rating: 4.7,
      reviews: 1692,
      badge: "Top pick",
      location: "Muscat, Oman",
      meetingPoint: "Marina pickup point, Muscat",
    },
    {
      id: "muscat-wadi-shab-bimmah-sinkhole",
      title: "From Muscat: Wadi Shab & Bimmah Sinkhole Full-Day Tour",
      description: "Explore the stunning Wadi Shab and the natural wonder of Bimmah Sinkhole.",
      duration: "3 - 9 hours • Small group • Pickup available",
      price: 3553,
      currency: "INR",
      image: "/assets/categories/city-tours/muscat-wadi-shab-bimmah-sinkhole/1.avif",
      gallery: [
        "/assets/categories/city-tours/muscat-wadi-shab-bimmah-sinkhole/2.avif",
        "/assets/categories/city-tours/muscat-wadi-shab-bimmah-sinkhole/3.avif",
      ],
      perks: ["Small group tour", "Hotel pickup", "Professional guide"],
      highlights: [
        "Swim in the turquoise pools of Wadi Shab",
        "Visit the natural Bimmah Sinkhole",
        "Enjoy scenic views of Oman's landscape",
      ],
      included: ["Transportation", "Professional guide", "Hotel pickup and drop-off"],
      essentials: ["Bring swimwear", "Comfortable walking shoes", "Camera for photos"],
      overview: "A full-day adventure exploring Wadi Shab's natural pools and the breathtaking Bimmah Sinkhole.",
      rating: 4.8,
      reviews: 1372,
      badge: "Traveler favorite",
      location: "Muscat, Oman",
      meetingPoint: "Hotel pickup within Muscat",
    },
    {
      id: "muscat-wahiba-sands-wadi-bani-khalid",
      title: "Muscat: Wahiba Sands Desert Tour and Wadi Bani Khalid Group",
      description: "Experience the desert dunes of Wahiba Sands and the oasis of Wadi Bani Khalid.",
      duration: "10 hours • Private group • Pickup available",
      price: 7994,
      currency: "INR",
      image: "/assets/categories/city-tours/muscat-wahiba-sands-wadi-bani-khalid/1.avif",
      gallery: [
        "/assets/categories/city-tours/muscat-wahiba-sands-wadi-bani-khalid/2.avif",
        "/assets/categories/city-tours/muscat-wahiba-sands-wadi-bani-khalid/3.avif",
        "/assets/categories/city-tours/muscat-wahiba-sands-wadi-bani-khalid/4.avif",
      ],
      perks: ["Private group", "Desert dune bashing", "Oasis visit"],
      highlights: [
        "Adventure through the golden dunes of Wahiba Sands",
        "Relax at the beautiful Wadi Bani Khalid oasis",
        "Experience traditional Bedouin culture",
      ],
      included: ["4WD transportation", "Professional guide", "Hotel pickup"],
      essentials: ["Wear comfortable clothing", "Bring sunglasses", "Camera recommended"],
      overview: "Journey through the desert and discover the natural beauty of Wahiba Sands and Wadi Bani Khalid.",
      rating: 4.6,
      reviews: 0,
      badge: "Adventure",
      location: "Muscat, Oman",
      meetingPoint: "Hotel pickup within Muscat",
    },
    {
      id: "muscat-daymaniyat-islands-bbq-lunch",
      title: "Muscat: Daymaniyat Islands Snorkeling Trip with BBQ Lunch",
      description: "Snorkel in pristine waters and enjoy a BBQ lunch on the Daymaniyat Islands.",
      duration: "5.5 hours",
      price: 7698,
      oldPrice: 9504,
      currency: "INR",
      image: "/assets/categories/city-tours/muscat-daymaniyat-islands-bbq-lunch/1.avif",
      gallery: [
        "/assets/categories/city-tours/muscat-daymaniyat-islands-bbq-lunch/2.avif",
        "/assets/categories/city-tours/muscat-daymaniyat-islands-bbq-lunch/3.avif",
      ],
      perks: ["BBQ lunch", "Snorkeling equipment", "Marine life viewing"],
      highlights: [
        "Snorkel in crystal-clear waters",
        "Enjoy a delicious BBQ lunch",
        "Spot diverse marine life",
      ],
      included: ["Snorkeling gear", "BBQ lunch", "Boat transfer", "Guide"],
      essentials: ["Swimwear required", "Sunscreen essential", "Waterproof bag"],
      overview: "An extended snorkeling adventure with BBQ lunch on the beautiful Daymaniyat Islands.",
      rating: 4.7,
      reviews: 498,
      badge: "Must try",
      location: "Muscat, Oman",
      meetingPoint: "Marina pickup point, Muscat",
    },
    {
      id: "muscat-wahiba-desert-wadi-bani-khalid-guided",
      title: "Muscat: Wahiba Desert and Wadi Bani Khalid Guided Group Tour",
      description: "Guided group tour through Wahiba Desert and Wadi Bani Khalid.",
      duration: "8 hours - 1.5 days • Small group • Pickup available",
      price: 8793,
      currency: "INR",
      image: "/assets/categories/city-tours/muscat-wahiba-desert-wadi-bani-khalid-guided/1.avif",
      gallery: [
        "/assets/categories/city-tours/muscat-wahiba-desert-wadi-bani-khalid-guided/2.webp",
        "/assets/categories/city-tours/muscat-wahiba-desert-wadi-bani-khalid-guided/3.webp",
      ],
      perks: ["Small group", "Expert guide", "Desert experience"],
      highlights: [
        "Explore Wahiba Desert dunes",
        "Visit Wadi Bani Khalid oasis",
        "Learn about local culture",
      ],
      included: ["Transportation", "Professional guide", "Hotel pickup"],
      essentials: ["Comfortable clothes", "Sun protection", "Camera"],
      overview: "A comprehensive guided tour combining desert adventure with oasis relaxation.",
      rating: 4.8,
      reviews: 533,
      badge: "Popular",
      location: "Muscat, Oman",
      meetingPoint: "Hotel pickup within Muscat",
    },
    {
      id: "muscat-4x4-jebel-akhdar-nizwa",
      title: "Muscat: 4x4 Adventure Through Jebel Akhdar and Nizwa",
      description: "4x4 adventure through the mountains of Jebel Akhdar and historic Nizwa.",
      duration: "9.5 hours • Small group • Pickup available",
      price: 11546,
      currency: "INR",
      image: "/assets/categories/city-tours/muscat-4x4-jebel-akhdar-nizwa/1.avif",
      gallery: [
        "/assets/categories/city-tours/muscat-4x4-jebel-akhdar-nizwa/2.avif",
      ],
      perks: ["4x4 vehicle", "Mountain views", "Historic sites"],
      highlights: [
        "Drive through Jebel Akhdar mountains",
        "Visit historic Nizwa Fort",
        "Enjoy panoramic mountain views",
      ],
      included: ["4x4 transportation", "Professional guide", "Hotel pickup"],
      essentials: ["Comfortable shoes", "Warm layers for mountains", "Camera"],
      overview: "An exciting 4x4 adventure exploring the mountains and historic sites of Oman.",
      rating: 4.9,
      reviews: 222,
      badge: "Top pick",
      location: "Muscat, Oman",
      meetingPoint: "Hotel pickup within Muscat",
    },
    {
      id: "muscat-budget-friendly-city-tour",
      title: "Muscat: Budget Friendly City Tour",
      description: "Affordable city tour exploring the highlights of Muscat.",
      duration: "4.5 hours • Small group • Pickup available",
      price: 4753,
      currency: "INR",
      image: "/assets/categories/city-tours/muscat-budget-friendly-city-tour/1.avif",
      gallery: [
        "/assets/categories/city-tours/muscat-budget-friendly-city-tour/2.avif",
        "/assets/categories/city-tours/muscat-budget-friendly-city-tour/3.avif",
      ],
      perks: ["Budget friendly", "City highlights", "Small group"],
      highlights: [
        "Visit Sultan Qaboos Grand Mosque",
        "Explore Mutrah Souq",
        "See Al Alam Palace",
      ],
      included: ["Transportation", "Professional guide", "Hotel pickup"],
      essentials: ["Modest clothing for mosque", "Comfortable shoes", "Water"],
      overview: "An affordable way to explore Muscat's main attractions and cultural sites.",
      rating: 4.9,
      reviews: 155,
      badge: "Budget",
      location: "Muscat, Oman",
      meetingPoint: "Hotel pickup within Muscat",
    },
    {
      id: "oman-hidden-gems-wadi-shab-bimmah",
      title: "Oman's Hidden Gems: Wadi Shab & Bimmah Sinkhole",
      description: "Discover hidden gems including Wadi Shab and Bimmah Sinkhole.",
      duration: "3 - 9 hours • Pickup available",
      price: 2665,
      currency: "INR",
      image: "/assets/categories/city-tours/oman-hidden-gems-wadi-shab-bimmah/1.avif",
      gallery: [
        "/assets/categories/city-tours/oman-hidden-gems-wadi-shab-bimmah/2.avif",
        "/assets/categories/city-tours/oman-hidden-gems-wadi-shab-bimmah/3.avif",
        "/assets/categories/city-tours/oman-hidden-gems-wadi-shab-bimmah/4.avif",
      ],
      perks: ["Hidden gems", "Natural pools", "Scenic views"],
      highlights: [
        "Swim in Wadi Shab's natural pools",
        "Visit the stunning Bimmah Sinkhole",
        "Explore off-the-beaten-path locations",
      ],
      included: ["Transportation", "Guide", "Hotel pickup"],
      essentials: ["Swimwear", "Towel", "Waterproof camera"],
      overview: "Uncover Oman's hidden natural wonders on this scenic adventure tour.",
      rating: 4.9,
      reviews: 200,
      badge: "Hidden gems",
      location: "Muscat, Oman",
      meetingPoint: "Hotel pickup within Muscat",
    },
    {
      id: "muscat-nizwa-jebel-akhdar-wonders",
      title: "From Muscat: Nizwa & Jebel Akhdar Wonders Adventure Day Trip",
      description: "Adventure day trip to Nizwa and the wonders of Jebel Akhdar.",
      duration: "9 - 10 hours • Small group • Pickup available",
      price: 11546,
      currency: "INR",
      image: "/assets/categories/city-tours/muscat-nizwa-jebel-akhdar-wonders/1.webp",
      gallery: [
        "/assets/categories/city-tours/muscat-nizwa-jebel-akhdar-wonders/2.webp",
        "/assets/categories/city-tours/muscat-nizwa-jebel-akhdar-wonders/3.webp",
      ],
      perks: ["Mountain adventure", "Historic sites", "Small group"],
      highlights: [
        "Explore Nizwa Fort and souq",
        "Drive through Jebel Akhdar mountains",
        "Enjoy breathtaking mountain scenery",
      ],
      included: ["Transportation", "Professional guide", "Hotel pickup"],
      essentials: ["Warm clothing", "Comfortable shoes", "Camera"],
      overview: "A full-day adventure exploring historic Nizwa and the stunning Jebel Akhdar mountains.",
      rating: 4.8,
      reviews: 372,
      badge: "Adventure",
      location: "Muscat, Oman",
      meetingPoint: "Hotel pickup within Muscat",
    },
    {
      id: "muscat-daymaniyat-islands-lunch-snacks",
      title: "Muscat: Daymaniyat Islands Snorkeling with lunch and snacks",
      description: "Snorkeling trip to Daymaniyat Islands with lunch and snacks included.",
      duration: "4.5 hours",
      price: 6855,
      oldPrice: 9429,
      currency: "INR",
      image: "/assets/categories/city-tours/muscat-daymaniyat-islands-lunch-snacks/1.avif",
      gallery: [
        "/assets/categories/city-tours/muscat-daymaniyat-islands-lunch-snacks/2.webp",
        "/assets/categories/city-tours/muscat-daymaniyat-islands-lunch-snacks/3.avif",
      ],
      perks: ["Lunch and snacks", "Snorkeling gear", "Marine exploration"],
      highlights: [
        "Snorkel in pristine waters",
        "Enjoy lunch and snacks",
        "Discover marine biodiversity",
      ],
      included: ["Snorkeling equipment", "Lunch and snacks", "Boat transfer"],
      essentials: ["Swimwear", "Sunscreen", "Waterproof bag"],
      overview: "A snorkeling adventure with refreshments on the beautiful Daymaniyat Islands.",
      rating: 4.8,
      reviews: 145,
      badge: "Popular",
      location: "Muscat, Oman",
      meetingPoint: "Marina pickup point, Muscat",
    },
    {
      id: "oman-desert-safari-wadi-adventure",
      title: "Oman: Desert Safari & Wadi Adventure Tour",
      description: "Multi-day desert safari and wadi adventure tour.",
      duration: "3 days • Private group • Pickup available",
      price: 22071,
      oldPrice: 27589,
      currency: "INR",
      image: "/assets/categories/city-tours/oman-desert-safari-wadi-adventure/1.avif",
      gallery: [
        "/assets/categories/city-tours/oman-desert-safari-wadi-adventure/2.avif",
      ],
      perks: ["Multi-day tour", "Private group", "Desert camping"],
      highlights: [
        "Experience desert safari",
        "Explore multiple wadis",
        "Overnight desert camping",
      ],
      included: ["Accommodation", "Meals", "Transportation", "Guide"],
      essentials: ["Camping gear", "Warm clothing", "Personal items"],
      overview: "An immersive 3-day adventure combining desert safari with wadi exploration.",
      rating: 4.5,
      reviews: 0,
      badge: "New activity",
      location: "Muscat, Oman",
      meetingPoint: "Hotel pickup within Muscat",
    },
    {
      id: "muscat-wadi-bani-khalid-oman-desert",
      title: "Muscat: Wadi Bani Khalid Oasis & Oman Desert Tour",
      description: "Tour combining Wadi Bani Khalid oasis with Oman desert experience.",
      duration: "10 hours • Small group • Pickup available",
      price: 11546,
      currency: "INR",
      image: "/assets/categories/city-tours/muscat-wadi-bani-khalid-oman-desert/1.webp",
      gallery: [
        "/assets/categories/city-tours/muscat-wadi-bani-khalid-oman-desert/2.avif",
        "/assets/categories/city-tours/muscat-wadi-bani-khalid-oman-desert/3.avif",
      ],
      perks: ["Oasis visit", "Desert experience", "Small group"],
      highlights: [
        "Relax at Wadi Bani Khalid oasis",
        "Explore Oman desert",
        "Experience local culture",
      ],
      included: ["Transportation", "Guide", "Hotel pickup"],
      essentials: ["Swimwear", "Comfortable clothes", "Camera"],
      overview: "A perfect blend of oasis relaxation and desert adventure.",
      rating: 4.8,
      reviews: 316,
      badge: "Popular",
      location: "Muscat, Oman",
      meetingPoint: "Hotel pickup within Muscat",
    },
    {
      id: "unforgettable-4x4-nizwa-arabia-grand-canyon",
      title: "Unforgettable 4x4 Trip to Nizwa & Arabia's Grand Canyon",
      description: "4x4 adventure to Nizwa and Arabia's Grand Canyon.",
      duration: "10 hours • Small group • Pickup available",
      price: 11546,
      currency: "INR",
      image: "/assets/categories/city-tours/unforgettable-4x4-nizwa-arabia-grand-canyon/1.avif",
      gallery: [
        "/assets/categories/city-tours/unforgettable-4x4-nizwa-arabia-grand-canyon/2.avif",
        "/assets/categories/city-tours/unforgettable-4x4-nizwa-arabia-grand-canyon/3.avif",
      ],
      perks: ["4x4 adventure", "Grand Canyon views", "Historic Nizwa"],
      highlights: [
        "Visit Arabia's Grand Canyon",
        "Explore historic Nizwa",
        "Enjoy spectacular mountain views",
      ],
      included: ["4x4 vehicle", "Professional guide", "Hotel pickup"],
      essentials: ["Warm layers", "Comfortable shoes", "Camera"],
      overview: "An unforgettable 4x4 journey to Nizwa and the breathtaking Arabia's Grand Canyon.",
      rating: 4.8,
      reviews: 184,
      badge: "Adventure",
      location: "Muscat, Oman",
      meetingPoint: "Hotel pickup within Muscat",
    },
    {
      id: "muscat-group-guided-city-tour-lunch-dinner",
      title: "Muscat: Group Guided City Tour with Pickup and Lunch/ Dinner",
      description: "Guided city tour with optional lunch or dinner included.",
      duration: "4.5 hours • Skip the line • Pickup available",
      price: 6856,
      oldPrice: 7372,
      currency: "INR",
      image: "/assets/categories/city-tours/muscat-group-guided-city-tour-lunch-dinner/1.avif",
      gallery: [
        "/assets/categories/city-tours/muscat-group-guided-city-tour-lunch-dinner/2.avif",
        "/assets/categories/city-tours/muscat-group-guided-city-tour-lunch-dinner/3.avif",
      ],
      perks: ["Skip the line", "Lunch or dinner", "Group tour"],
      highlights: [
        "Visit major city attractions",
        "Enjoy local cuisine",
        "Learn about Muscat's history",
      ],
      included: ["Transportation", "Guide", "Lunch or dinner", "Hotel pickup"],
      essentials: ["Modest clothing", "Comfortable shoes", "Appetite"],
      overview: "A comprehensive city tour with the option to enjoy local lunch or dinner.",
      rating: 4.5,
      reviews: 71,
      badge: "City tour",
      location: "Muscat, Oman",
      meetingPoint: "Hotel pickup within Muscat",
    },
    {
      id: "muscat-wahiba-sands-wadi-bani-khalid-mudayrib",
      title: "Muscat: Wahiba Sands, Wadi Bani Khalid & Mudayrib Tour",
      description: "Tour combining Wahiba Sands, Wadi Bani Khalid, and Mudayrib.",
      duration: "10 hours • Small group • Pickup available",
      price: 8704,
      currency: "INR",
      image: "/assets/categories/city-tours/muscat-wahiba-sands-wadi-bani-khalid-mudayrib/1.avif",
      gallery: [
        "/assets/categories/city-tours/muscat-wahiba-sands-wadi-bani-khalid-mudayrib/2.avif",
        "/assets/categories/city-tours/muscat-wahiba-sands-wadi-bani-khalid-mudayrib/3.avif",
      ],
      perks: ["Desert dunes", "Oasis visit", "Historic Mudayrib"],
      highlights: [
        "Explore Wahiba Sands desert",
        "Visit Wadi Bani Khalid",
        "Discover Mudayrib village",
      ],
      included: ["Transportation", "Guide", "Hotel pickup"],
      essentials: ["Comfortable clothing", "Swimwear", "Camera"],
      overview: "A comprehensive tour exploring desert, oasis, and historic village.",
      rating: 4.8,
      reviews: 49,
      badge: "Comprehensive",
      location: "Muscat, Oman",
      meetingPoint: "Hotel pickup within Muscat",
    },
    {
      id: "muscat-nizwa-oman-historical-gems",
      title: "From Muscat: Nizwa and Oman's Historical Gems Tour",
      description: "Explore Nizwa and Oman's historical gems on this guided tour.",
      duration: "8 - 10 hours • Small group • Pickup available",
      price: 7994,
      oldPrice: 8882,
      currency: "INR",
      image: "/assets/categories/city-tours/muscat-nizwa-oman-historical-gems/1.avif",
      gallery: [
        "/assets/categories/city-tours/muscat-nizwa-oman-historical-gems/2.avif",
        "/assets/categories/city-tours/muscat-nizwa-oman-historical-gems/3.avif",
      ],
      perks: ["Historical sites", "Small group", "Expert guide"],
      highlights: [
        "Visit Nizwa Fort and souq",
        "Explore historical sites",
        "Learn about Omani culture",
      ],
      included: ["Transportation", "Professional guide", "Hotel pickup"],
      essentials: ["Comfortable shoes", "Modest clothing", "Camera"],
      overview: "Discover Nizwa and other historical gems of Oman on this cultural tour.",
      rating: 4.7,
      reviews: 301,
      badge: "Historical",
      location: "Muscat, Oman",
      meetingPoint: "Hotel pickup within Muscat",
    },
    {
      id: "oman-private-city-tour-muscat",
      title: "Oman: Private City Tour of Muscat with pick up/drop off",
      description: "Private city tour of Muscat with personalized service.",
      duration: "4.5 hours • Skip the line • Pickup available",
      price: 13500,
      oldPrice: 14211,
      currency: "INR",
      image: "/assets/categories/city-tours/oman-private-city-tour-muscat/1.webp",
      gallery: [
        "/assets/categories/city-tours/oman-private-city-tour-muscat/2.avif",
        "/assets/categories/city-tours/oman-private-city-tour-muscat/3.avif",
      ],
      perks: ["Private tour", "Skip the line", "Personalized service"],
      highlights: [
        "Private guide for your group",
        "Visit key Muscat attractions",
        "Flexible itinerary",
      ],
      included: ["Private transportation", "Personal guide", "Hotel pickup"],
      essentials: ["Modest clothing", "Comfortable shoes", "Camera"],
      overview: "A private, personalized tour of Muscat tailored to your interests.",
      rating: 4.3,
      reviews: 69,
      badge: "Private",
      location: "Muscat, Oman",
      meetingPoint: "Hotel pickup within Muscat",
    },
    {
      id: "muscat-full-day-wadi-shab-bimmah-sinkhole-private",
      title: "Muscat: Full-Day Wadi Shab & Bimmah Sinkhole Private Tour",
      description: "Private full-day tour to Wadi Shab and Bimmah Sinkhole.",
      duration: "8 hours • Private group • Pickup available",
      price: 11546,
      currency: "INR",
      image: "/assets/categories/city-tours/muscat-full-day-wadi-shab-bimmah-sinkhole-private/1.avif",
      gallery: [
        "/assets/categories/city-tours/muscat-full-day-wadi-shab-bimmah-sinkhole-private/2.avif",
        "/assets/categories/city-tours/muscat-full-day-wadi-shab-bimmah-sinkhole-private/3.avif",
      ],
      perks: ["Private group", "Full day", "Flexible schedule"],
      highlights: [
        "Private tour to Wadi Shab",
        "Visit Bimmah Sinkhole",
        "Personalized experience",
      ],
      included: ["Private transportation", "Personal guide", "Hotel pickup"],
      essentials: ["Swimwear", "Towel", "Waterproof camera"],
      overview: "A private full-day adventure to Wadi Shab and Bimmah Sinkhole.",
      rating: 5.0,
      reviews: 76,
      badge: "Private",
      location: "Muscat, Oman",
      meetingPoint: "Hotel pickup within Muscat",
    },
    {
      id: "muscat-daymaniat-islands-snorkeling-refreshments",
      title: "Muscat: Daymaniat Islands Snorkeling Tour with Refreshments",
      description: "Snorkeling tour to Daymaniat Islands with refreshments included.",
      duration: "4.5 hours • Optional audio guide",
      price: 7000,
      oldPrice: 9816,
      currency: "INR",
      image: "/assets/categories/city-tours/muscat-daymaniat-islands-snorkeling-refreshments/1.avif",
      gallery: [
        "/assets/categories/city-tours/muscat-daymaniat-islands-snorkeling-refreshments/2.avif",
        "/assets/categories/city-tours/muscat-daymaniat-islands-snorkeling-refreshments/3.avif",
      ],
      perks: ["Refreshments", "Audio guide option", "Snorkeling gear"],
      highlights: [
        "Snorkel in clear waters",
        "Enjoy refreshments",
        "Learn about marine life",
      ],
      included: ["Snorkeling equipment", "Refreshments", "Boat transfer"],
      essentials: ["Swimwear", "Sunscreen", "Waterproof bag"],
      overview: "A snorkeling tour with refreshments on the beautiful Daymaniat Islands.",
      rating: 4.7,
      reviews: 401,
      badge: "Popular",
      location: "Muscat, Oman",
      meetingPoint: "Marina pickup point, Muscat",
    },
    {
      id: "muscat-daymaniat-islands-tour",
      title: "Muscat: Daymaniat Islands Tour",
      description: "Tour of the beautiful Daymaniat Islands.",
      duration: "5 hours • Skip the line",
      price: 7105,
      oldPrice: 8882,
      currency: "INR",
      image: "/assets/categories/city-tours/muscat-daymaniat-islands-tour/1.avif",
      gallery: [
        "/assets/categories/city-tours/muscat-daymaniat-islands-tour/2.webp",
      ],
      perks: ["Skip the line", "Island exploration", "Boat tour"],
      highlights: [
        "Explore Daymaniat Islands",
        "Enjoy boat ride",
        "Experience natural beauty",
      ],
      included: ["Boat transfer", "Guide", "Island access"],
      essentials: ["Comfortable clothes", "Sunscreen", "Camera"],
      overview: "A tour exploring the natural beauty of Daymaniat Islands.",
      rating: 4.9,
      reviews: 79,
      badge: "Island tour",
      location: "Muscat, Oman",
      meetingPoint: "Marina pickup point, Muscat",
    },
    {
      id: "muscat-full-day-city-tour",
      title: "Muscat: Full-Day City Tour",
      description: "Comprehensive full-day tour of Muscat city.",
      duration: "7 hours • Pickup available",
      price: 7105,
      currency: "INR",
      image: "/assets/categories/city-tours/muscat-full-day-city-tour/1.avif",
      gallery: [
        "/assets/categories/city-tours/muscat-full-day-city-tour/2.avif",
      ],
      perks: ["Full day", "City highlights", "Comprehensive tour"],
      highlights: [
        "Visit all major attractions",
        "Learn about Muscat history",
        "Experience local culture",
      ],
      included: ["Transportation", "Professional guide", "Hotel pickup"],
      essentials: ["Modest clothing", "Comfortable shoes", "Water"],
      overview: "A comprehensive full-day tour covering all major attractions of Muscat.",
      rating: 4.8,
      reviews: 91,
      badge: "City tour",
      location: "Muscat, Oman",
      meetingPoint: "Hotel pickup within Muscat",
    },
    {
      id: "oman-daymaniyat-islands-snorkeling-trip",
      title: "Oman: Daymaniyat Islands Snorkeling Trip",
      description: "Snorkeling trip to the pristine Daymaniyat Islands.",
      duration: "5 hours",
      price: 7026,
      oldPrice: 8266,
      currency: "INR",
      image: "/assets/categories/city-tours/oman-daymaniyat-islands-snorkeling-trip/1.avif",
      gallery: [
        "/assets/categories/city-tours/oman-daymaniyat-islands-snorkeling-trip/2.avif",
        "/assets/categories/city-tours/oman-daymaniyat-islands-snorkeling-trip/3.avif",
      ],
      perks: ["Snorkeling", "Marine life", "Island beauty"],
      highlights: [
        "Snorkel in pristine waters",
        "Discover marine biodiversity",
        "Enjoy island scenery",
      ],
      included: ["Snorkeling equipment", "Boat transfer", "Guide"],
      essentials: ["Swimwear", "Sunscreen", "Waterproof camera"],
      overview: "A snorkeling adventure exploring the underwater world of Daymaniyat Islands.",
      rating: 5.0,
      reviews: 60,
      badge: "Top pick",
      location: "Muscat, Oman",
      meetingPoint: "Marina pickup point, Muscat",
    },
    {
      id: "muscat-wadi-shab-romantic-cave-sinkhole",
      title: "Muscat: Wadi Shab, Romantic Cave and Sinkhole Full-day Trip",
      description: "Full-day trip to Wadi Shab, Romantic Cave, and Sinkhole.",
      duration: "2.5 - 9 hours • Small group • Pickup available",
      price: 2842,
      oldPrice: 3553,
      currency: "INR",
      image: "/assets/categories/city-tours/muscat-wadi-shab-romantic-cave-sinkhole/1.avif",
      gallery: [
        "/assets/categories/city-tours/muscat-wadi-shab-romantic-cave-sinkhole/2.avif",
        "/assets/categories/city-tours/muscat-wadi-shab-romantic-cave-sinkhole/3.avif",
      ],
      perks: ["Romantic Cave", "Sinkhole visit", "Small group"],
      highlights: [
        "Explore Wadi Shab",
        "Visit Romantic Cave",
        "See Bimmah Sinkhole",
      ],
      included: ["Transportation", "Guide", "Hotel pickup"],
      essentials: ["Swimwear", "Towel", "Waterproof bag"],
      overview: "A full-day adventure visiting Wadi Shab, Romantic Cave, and the sinkhole.",
      rating: 4.7,
      reviews: 95,
      badge: "Adventure",
      location: "Muscat, Oman",
      meetingPoint: "Hotel pickup within Muscat",
    },
    {
      id: "muscat-private-city-guided-tour",
      title: "Muscat: Private City Guided Tour",
      description: "Private guided tour of Muscat city.",
      duration: "4.5 hours • Pickup available",
      price: 8793,
      currency: "INR",
      image: "/assets/categories/city-tours/muscat-private-city-guided-tour/1.avif",
      gallery: [
        "/assets/categories/city-tours/muscat-private-city-guided-tour/2.webp",
        "/assets/categories/city-tours/muscat-private-city-guided-tour/3.webp",
      ],
      perks: ["Private tour", "Personal guide", "Flexible itinerary"],
      highlights: [
        "Private guide",
        "Visit key attractions",
        "Personalized experience",
      ],
      included: ["Private transportation", "Personal guide", "Hotel pickup"],
      essentials: ["Modest clothing", "Comfortable shoes", "Camera"],
      overview: "A private guided tour of Muscat tailored to your preferences.",
      rating: 5.0,
      reviews: 49,
      badge: "Private",
      location: "Muscat, Oman",
      meetingPoint: "Hotel pickup within Muscat",
    },
  ],
  "car-rental": [
    {
      id: "muscat-private-transfer-to-dubai",
      title: "Muscat : Private transfer from Muscat to Dubai",
      description: "Private transfer service from Muscat to Dubai with comfortable vehicle and professional driver.",
      duration: "4 hours • Skip the line • Private group",
      price: 41332,
      currency: "INR",
      image: "/assets/categories/car-rental/muscat-private-transfer-to-dubai/1.webp",
      gallery: [
        "/assets/categories/car-rental/muscat-private-transfer-to-dubai/2.avif",
        "/assets/categories/car-rental/muscat-private-transfer-to-dubai/3.webp",
      ],
      perks: ["Private group", "Skip the line", "Comfortable vehicle"],
      highlights: [
        "Private transfer from Muscat to Dubai",
        "Professional English-speaking driver",
        "Comfortable vehicle for up to 6 passengers",
      ],
      included: ["Private vehicle", "Professional driver", "Border crossing assistance"],
      essentials: ["Valid passport required", "Border crossing documents", "Comfortable travel"],
      overview: "A comfortable private transfer service from Muscat to Dubai with professional driver.",
      rating: 4.8,
      reviews: 4,
      badge: "Top pick",
      location: "Muscat, Oman",
      meetingPoint: "Pickup from Muscat location",
    },
    {
      id: "muscat-half-day-vehicle-hire",
      title: "Muscat: Half-Day Vehicle Hire with English-Speaking Driver",
      description: "Half-day vehicle hire with professional English-speaking driver in Muscat.",
      duration: "4 hours • Pickup available",
      price: 17675,
      currency: "INR",
      image: "/assets/categories/car-rental/muscat-half-day-vehicle-hire/1.avif",
      gallery: [
        "/assets/categories/car-rental/muscat-half-day-vehicle-hire/2.webp",
        "/assets/categories/car-rental/muscat-half-day-vehicle-hire/3.webp",
      ],
      perks: ["English-speaking driver", "Half-day hire", "Hotel pickup"],
      highlights: [
        "Professional English-speaking driver",
        "Comfortable vehicle for up to 4 passengers",
        "Flexible itinerary",
      ],
      included: ["Vehicle with driver", "Hotel pickup", "4 hours service"],
      essentials: ["Valid ID required", "Comfortable clothing", "Camera"],
      overview: "Half-day vehicle hire with professional English-speaking driver for exploring Muscat.",
      rating: 5.0,
      reviews: 1,
      badge: "Popular",
      location: "Muscat, Oman",
      meetingPoint: "Hotel pickup within Muscat",
    },
    {
      id: "muscat-group-guided-city-tour-car",
      title: "Muscat: Group Guided City Tour with Pickup and Lunch/ Dinner",
      description: "Group guided city tour with optional lunch or dinner included.",
      duration: "4.5 hours • Skip the line • Pickup available",
      price: 6856,
      oldPrice: 7372,
      currency: "INR",
      image: "/assets/categories/car-rental/muscat-group-guided-city-tour-car/1.avif",
      gallery: [
        "/assets/categories/car-rental/muscat-group-guided-city-tour-car/2.avif",
        "/assets/categories/car-rental/muscat-group-guided-city-tour-car/3.avif",
      ],
      perks: ["Group tour", "Lunch or dinner", "Skip the line"],
      highlights: [
        "Visit major city attractions",
        "Enjoy local cuisine",
        "Learn about Muscat's history",
      ],
      included: ["Transportation", "Guide", "Lunch or dinner", "Hotel pickup"],
      essentials: ["Modest clothing", "Comfortable shoes", "Appetite"],
      overview: "A comprehensive city tour with the option to enjoy local lunch or dinner.",
      rating: 4.5,
      reviews: 71,
      badge: "City tour",
      location: "Muscat, Oman",
      meetingPoint: "Hotel pickup within Muscat",
    },
    {
      id: "best-private-transfer-muscat-airport",
      title: "Best Private Transfer From Muscat Airport",
      description: "Premium private transfer service from Muscat Airport with professional driver.",
      duration: "40 minutes • Private group • Pickup available",
      price: 4885,
      currency: "INR",
      image: "/assets/categories/car-rental/best-private-transfer-muscat-airport/1.webp",
      gallery: [
        "/assets/categories/car-rental/best-private-transfer-muscat-airport/2.avif",
        "/assets/categories/car-rental/best-private-transfer-muscat-airport/3.avif",
      ],
      perks: ["Private group", "Airport pickup", "Professional driver"],
      highlights: [
        "Meet and greet at airport",
        "Comfortable vehicle for up to 7 passengers",
        "Luggage assistance",
      ],
      included: ["Private vehicle", "Professional driver", "Airport pickup"],
      essentials: ["Flight details required", "Valid ID", "Comfortable travel"],
      overview: "Premium private transfer service from Muscat Airport to your destination.",
      rating: 4.3,
      reviews: 0,
      badge: "Airport transfer",
      location: "Muscat, Oman",
      meetingPoint: "Muscat Airport arrivals",
    },
    {
      id: "muscat-4-hours-private-city-tour",
      title: "Muscat : 4 hours private Tour of Muscat City with Pick-up",
      description: "Private 4-hour tour of Muscat City with hotel pickup included.",
      duration: "4 hours • Pickup available",
      price: 20563,
      currency: "INR",
      image: "/assets/categories/car-rental/muscat-4-hours-private-city-tour/1.webp",
      gallery: [
        "/assets/categories/car-rental/muscat-4-hours-private-city-tour/2.avif",
        "/assets/categories/car-rental/muscat-4-hours-private-city-tour/3.webp",
      ],
      perks: ["Private tour", "Hotel pickup", "Flexible itinerary"],
      highlights: [
        "Private guide and vehicle",
        "Visit key Muscat attractions",
        "Personalized experience",
      ],
      included: ["Private vehicle", "Professional guide", "Hotel pickup"],
      essentials: ["Modest clothing", "Comfortable shoes", "Camera"],
      overview: "A private 4-hour tour of Muscat City tailored to your interests.",
      rating: 4.7,
      reviews: 84,
      badge: "Private",
      location: "Muscat, Oman",
      meetingPoint: "Hotel pickup within Muscat",
    },
    {
      id: "muscat-full-day-city-tour-car",
      title: "Muscat: Full-Day City Tour",
      description: "Comprehensive full-day tour of Muscat city.",
      duration: "7 hours • Pickup available",
      price: 7105,
      currency: "INR",
      image: "/assets/categories/car-rental/muscat-full-day-city-tour-car/1.avif",
      gallery: [
        "/assets/categories/car-rental/muscat-full-day-city-tour-car/2.avif",
        "/assets/categories/car-rental/muscat-full-day-city-tour-car/3.avif",
      ],
      perks: ["Full day", "City highlights", "Comprehensive tour"],
      highlights: [
        "Visit all major attractions",
        "Learn about Muscat history",
        "Experience local culture",
      ],
      included: ["Transportation", "Professional guide", "Hotel pickup"],
      essentials: ["Modest clothing", "Comfortable shoes", "Water"],
      overview: "A comprehensive full-day tour covering all major attractions of Muscat.",
      rating: 4.8,
      reviews: 91,
      badge: "City tour",
      location: "Muscat, Oman",
      meetingPoint: "Hotel pickup within Muscat",
    },
    {
      id: "muscat-budget-friendly-city-tour-car",
      title: "Muscat: Budget Friendly City Tour",
      description: "Affordable city tour exploring the highlights of Muscat.",
      duration: "4.5 hours • Small group • Pickup available",
      price: 4753,
      currency: "INR",
      image: "/assets/categories/car-rental/muscat-budget-friendly-city-tour-car/1.avif",
      gallery: [
        "/assets/categories/car-rental/muscat-budget-friendly-city-tour-car/2.avif",
        "/assets/categories/car-rental/muscat-budget-friendly-city-tour-car/3.avif",
      ],
      perks: ["Budget friendly", "City highlights", "Small group"],
      highlights: [
        "Visit Sultan Qaboos Grand Mosque",
        "Explore Mutrah Souq",
        "See Al Alam Palace",
      ],
      included: ["Transportation", "Professional guide", "Hotel pickup"],
      essentials: ["Modest clothing for mosque", "Comfortable shoes", "Water"],
      overview: "An affordable way to explore Muscat's main attractions and cultural sites.",
      rating: 4.9,
      reviews: 155,
      badge: "Top rated",
      location: "Muscat, Oman",
      meetingPoint: "Hotel pickup within Muscat",
    },
    {
      id: "oman-private-muscat-city-tour-pickup",
      title: "Oman: Private Muscat City Tour With Pick-up/ Drop-off",
      description: "Private city tour of Muscat with pickup and drop-off service.",
      duration: "4.5 hours • Skip the line • Pickup available",
      price: 13767,
      currency: "INR",
      image: "/assets/categories/car-rental/oman-private-muscat-city-tour-pickup/1.avif",
      gallery: [
        "/assets/categories/car-rental/oman-private-muscat-city-tour-pickup/2.avif",
        "/assets/categories/car-rental/oman-private-muscat-city-tour-pickup/3.avif",
      ],
      perks: ["Private tour", "Skip the line", "Pickup and drop-off"],
      highlights: [
        "Private guide and vehicle",
        "Visit key attractions",
        "Flexible itinerary",
      ],
      included: ["Private vehicle", "Professional guide", "Hotel pickup and drop-off"],
      essentials: ["Modest clothing", "Comfortable shoes", "Camera"],
      overview: "A private city tour of Muscat with convenient pickup and drop-off service.",
      rating: 4.2,
      reviews: 177,
      badge: "Private",
      location: "Muscat, Oman",
      meetingPoint: "Hotel pickup within Muscat",
    },
    {
      id: "best-muscat-airport-transfer",
      title: "The Best Muscat Airport Transfer",
      description: "Premium airport transfer service in Muscat with professional driver.",
      duration: "45 minutes",
      price: 3997,
      currency: "INR",
      image: "/assets/categories/car-rental/best-muscat-airport-transfer/1.avif",
      gallery: [
        "/assets/categories/car-rental/best-muscat-airport-transfer/2.webp",
        "/assets/categories/car-rental/best-muscat-airport-transfer/3.avif",
      ],
      perks: ["Airport transfer", "Professional driver", "Comfortable vehicle"],
      highlights: [
        "Meet and greet service",
        "Comfortable vehicle for up to 4 passengers",
        "Luggage assistance",
      ],
      included: ["Private vehicle", "Professional driver", "Airport pickup"],
      essentials: ["Flight details", "Valid ID", "Comfortable travel"],
      overview: "The best airport transfer service in Muscat with professional driver.",
      rating: 5.0,
      reviews: 3,
      badge: "Airport transfer",
      location: "Muscat, Oman",
      meetingPoint: "Muscat Airport",
    },
    {
      id: "muscat-evening-guided-city-highlights-van",
      title: "Muscat: Evening Guided City Highlights Tour by Van",
      description: "Evening guided city highlights tour by comfortable van.",
      duration: "3 hours • Pickup available",
      price: 3197,
      oldPrice: 3553,
      currency: "INR",
      image: "/assets/categories/car-rental/muscat-evening-guided-city-highlights-van/1.avif",
      gallery: [
        "/assets/categories/car-rental/muscat-evening-guided-city-highlights-van/2.avif",
        "/assets/categories/car-rental/muscat-evening-guided-city-highlights-van/3.avif",
      ],
      perks: ["Evening tour", "Van transportation", "City highlights"],
      highlights: [
        "Evening city tour",
        "Visit illuminated landmarks",
        "Comfortable van transportation",
      ],
      included: ["Van transportation", "Professional guide", "Hotel pickup"],
      essentials: ["Comfortable clothing", "Camera", "Evening attire"],
      overview: "An evening guided tour of Muscat's highlights by comfortable van.",
      rating: 4.8,
      reviews: 136,
      badge: "Top rated",
      location: "Muscat, Oman",
      meetingPoint: "Hotel pickup within Muscat",
    },
    {
      id: "muscat-private-city-guided-tour-car",
      title: "Muscat: Private City Guided Tour",
      description: "Private guided tour of Muscat city.",
      duration: "4.5 hours • Pickup available",
      price: 8793,
      currency: "INR",
      image: "/assets/categories/car-rental/muscat-private-city-guided-tour-car/1.avif",
      gallery: [
        "/assets/categories/car-rental/muscat-private-city-guided-tour-car/2.webp",
        "/assets/categories/car-rental/muscat-private-city-guided-tour-car/3.webp",
      ],
      perks: ["Private tour", "Personal guide", "Flexible itinerary"],
      highlights: [
        "Private guide",
        "Visit key attractions",
        "Personalized experience",
      ],
      included: ["Private transportation", "Personal guide", "Hotel pickup"],
      essentials: ["Modest clothing", "Comfortable shoes", "Camera"],
      overview: "A private guided tour of Muscat tailored to your preferences.",
      rating: 5.0,
      reviews: 49,
      badge: "Private",
      location: "Muscat, Oman",
      meetingPoint: "Hotel pickup within Muscat",
    },
    {
      id: "muscat-city-highlights-tour-optional-transfers",
      title: "Muscat: City Highlights Tour with Optional Transfers",
      description: "City highlights tour with optional transfer services.",
      duration: "4 - 7 hours • Pickup available",
      price: 3553,
      currency: "INR",
      image: "/assets/categories/car-rental/muscat-city-highlights-tour-optional-transfers/1.avif",
      gallery: [
        "/assets/categories/car-rental/muscat-city-highlights-tour-optional-transfers/2.avif",
        "/assets/categories/car-rental/muscat-city-highlights-tour-optional-transfers/3.avif",
      ],
      perks: ["City highlights", "Optional transfers", "Flexible duration"],
      highlights: [
        "Visit major city attractions",
        "Optional transfer services",
        "Flexible tour duration",
      ],
      included: ["Transportation", "Professional guide", "Optional transfers"],
      essentials: ["Modest clothing", "Comfortable shoes", "Camera"],
      overview: "A city highlights tour with optional transfer services for your convenience.",
      rating: 4.8,
      reviews: 159,
      badge: "Top rated",
      location: "Muscat, Oman",
      meetingPoint: "Hotel pickup within Muscat",
    },
    {
      id: "oman-private-city-tour-muscat-pickup-dropoff",
      title: "Oman: Private City Tour of Muscat with pick up/drop off",
      description: "Private city tour of Muscat with personalized service.",
      duration: "4.5 hours • Skip the line • Pickup available",
      price: 13500,
      oldPrice: 14211,
      currency: "INR",
      image: "/assets/categories/car-rental/oman-private-city-tour-muscat-pickup-dropoff/1.avif",
      gallery: [
        "/assets/categories/car-rental/oman-private-city-tour-muscat-pickup-dropoff/2.avif",
        "/assets/categories/car-rental/oman-private-city-tour-muscat-pickup-dropoff/3.avif",
      ],
      perks: ["Private tour", "Skip the line", "Personalized service"],
      highlights: [
        "Private guide for your group",
        "Visit key Muscat attractions",
        "Flexible itinerary",
      ],
      included: ["Private transportation", "Personal guide", "Hotel pickup"],
      essentials: ["Modest clothing", "Comfortable shoes", "Camera"],
      overview: "A private, personalized tour of Muscat tailored to your interests.",
      rating: 4.3,
      reviews: 69,
      badge: "Private",
      location: "Muscat, Oman",
      meetingPoint: "Hotel pickup within Muscat",
    },
    {
      id: "muscat-big-bus-hop-on-hop-off",
      title: "Muscat: Big Bus Hop-On Hop-Off Sightseeing Tour",
      description: "Hop-on hop-off sightseeing tour of Muscat with flexible itinerary.",
      duration: "1 - 2 days • Optional audio guide",
      price: 7550,
      currency: "INR",
      image: "/assets/categories/car-rental/muscat-big-bus-hop-on-hop-off/1.avif",
      gallery: [
        "/assets/categories/car-rental/muscat-big-bus-hop-on-hop-off/2.avif",
        "/assets/categories/car-rental/muscat-big-bus-hop-on-hop-off/3.avif",
      ],
      perks: ["Hop-on hop-off", "1-2 days validity", "Audio guide option"],
      highlights: [
        "Flexible sightseeing",
        "Multiple stops",
        "Audio guide available",
      ],
      included: ["Bus ticket", "Audio guide (optional)", "Multiple stops"],
      essentials: ["Comfortable shoes", "Camera", "Water"],
      overview: "A flexible hop-on hop-off sightseeing tour of Muscat with 1-2 days validity.",
      rating: 3.9,
      reviews: 95,
      badge: "Certified by GetYourGuide",
      location: "Muscat, Oman",
      meetingPoint: "Various stops in Muscat",
    },
    {
      id: "muscat-half-day-city-tour-audio-guiding",
      title: "Muscat Half-Day City Tour with Audio Guiding",
      description: "Half-day city tour with audio guide for self-paced exploration.",
      duration: "4 hours • Pickup available • Optional audio guide",
      price: 5329,
      currency: "INR",
      image: "/assets/categories/car-rental/muscat-half-day-city-tour-audio-guiding/1.avif",
      gallery: [
        "/assets/categories/car-rental/muscat-half-day-city-tour-audio-guiding/2.avif",
        "/assets/categories/car-rental/muscat-half-day-city-tour-audio-guiding/3.avif",
      ],
      perks: ["Audio guide", "Half-day tour", "Hotel pickup"],
      highlights: [
        "Self-paced exploration",
        "Audio guide included",
        "Visit key attractions",
      ],
      included: ["Transportation", "Audio guide", "Hotel pickup"],
      essentials: ["Comfortable shoes", "Headphones", "Camera"],
      overview: "A half-day city tour with audio guide for self-paced exploration of Muscat.",
      rating: 4.2,
      reviews: 584,
      badge: "Audio tour",
      location: "Muscat, Oman",
      meetingPoint: "Hotel pickup within Muscat",
    },
    {
      id: "muscat-evening-group-city-tour-free-dinner",
      title: "Muscat :evening group city tour with pick-up & free dinner",
      description: "Evening group city tour with free dinner included.",
      duration: "4.5 hours • Skip the line • Pickup available",
      price: 6750,
      oldPrice: 7105,
      currency: "INR",
      image: "/assets/categories/car-rental/muscat-evening-group-city-tour-free-dinner/1.avif",
      gallery: [
        "/assets/categories/car-rental/muscat-evening-group-city-tour-free-dinner/2.avif",
        "/assets/categories/car-rental/muscat-evening-group-city-tour-free-dinner/3.avif",
      ],
      perks: ["Evening tour", "Free dinner", "Group tour"],
      highlights: [
        "Evening city exploration",
        "Free dinner included",
        "Group experience",
      ],
      included: ["Transportation", "Guide", "Free dinner", "Hotel pickup"],
      essentials: ["Evening attire", "Appetite", "Camera"],
      overview: "An evening group city tour with free dinner included.",
      rating: 5.0,
      reviews: 10,
      badge: "Evening tour",
      location: "Muscat, Oman",
      meetingPoint: "Hotel pickup within Muscat",
    },
    {
      id: "muscat-group-city-tour-lunch-dinner",
      title: "Muscat: Group City Tour with Pickup and Lunch or Dinner",
      description: "Group city tour with pickup and optional lunch or dinner.",
      duration: "5 hours • Skip the line • Pickup available",
      price: 6328,
      oldPrice: 6661,
      currency: "INR",
      image: "/assets/categories/car-rental/muscat-group-city-tour-lunch-dinner/1.webp",
      gallery: [
        "/assets/categories/car-rental/muscat-group-city-tour-lunch-dinner/2.webp",
        "/assets/categories/car-rental/muscat-group-city-tour-lunch-dinner/3.avif",
      ],
      perks: ["Group tour", "Lunch or dinner", "Skip the line"],
      highlights: [
        "City tour experience",
        "Lunch or dinner option",
        "Group exploration",
      ],
      included: ["Transportation", "Guide", "Lunch or dinner", "Hotel pickup"],
      essentials: ["Modest clothing", "Appetite", "Camera"],
      overview: "A group city tour with pickup and optional lunch or dinner.",
      rating: 4.2,
      reviews: 78,
      badge: "Group tour",
      location: "Muscat, Oman",
      meetingPoint: "Hotel pickup within Muscat",
    },
    {
      id: "muscat-full-day-car-driver-hire",
      title: "Muscat: Full-Day Car and Driver Hire in Muscat CityTerritory",
      description: "Full-day car and driver hire service in Muscat city territory.",
      duration: "9 hours • Skip the line • Private group",
      price: 23537,
      currency: "INR",
      image: "/assets/categories/car-rental/muscat-full-day-car-driver-hire/1.webp",
      gallery: [
        "/assets/categories/car-rental/muscat-full-day-car-driver-hire/2.webp",
        "/assets/categories/car-rental/muscat-full-day-car-driver-hire/3.avif",
      ],
      perks: ["Full day", "Private group", "Professional driver"],
      highlights: [
        "Full-day service",
        "Private vehicle and driver",
        "Flexible itinerary",
      ],
      included: ["Vehicle with driver", "9 hours service", "Hotel pickup"],
      essentials: ["Valid ID", "Comfortable clothing", "Camera"],
      overview: "Full-day car and driver hire service for exploring Muscat city territory.",
      rating: 4.3,
      reviews: 4,
      badge: "Full day",
      location: "Muscat, Oman",
      meetingPoint: "Hotel pickup within Muscat",
    },
    {
      id: "muscat-guided-landmarks-tour",
      title: "Muscat: Guided Landmarks Tour",
      description: "Guided tour of Muscat's famous landmarks and attractions.",
      duration: "5 hours • Pickup available",
      price: 7994,
      currency: "INR",
      image: "/assets/categories/car-rental/muscat-guided-landmarks-tour/1.webp",
      gallery: [
        "/assets/categories/car-rental/muscat-guided-landmarks-tour/2.avif",
        "/assets/categories/car-rental/muscat-guided-landmarks-tour/3.webp",
      ],
      perks: ["Landmarks tour", "Professional guide", "Hotel pickup"],
      highlights: [
        "Visit famous landmarks",
        "Learn about history",
        "Professional guide",
      ],
      included: ["Transportation", "Professional guide", "Hotel pickup"],
      essentials: ["Modest clothing", "Comfortable shoes", "Camera"],
      overview: "A guided tour exploring Muscat's famous landmarks and attractions.",
      rating: 4.8,
      reviews: 116,
      badge: "Top rated",
      location: "Muscat, Oman",
      meetingPoint: "Hotel pickup within Muscat",
    },
    {
      id: "muscat-tour-half-day",
      title: "Muscat Tour - Half day",
      description: "Half-day tour of Muscat with flexible duration options.",
      duration: "4 hours - 5 days • Small group • Pickup available",
      price: 6587,
      oldPrice: 7750,
      currency: "INR",
      image: "/assets/categories/car-rental/muscat-tour-half-day/1.avif",
      gallery: [
        "/assets/categories/car-rental/muscat-tour-half-day/2.avif",
        "/assets/categories/car-rental/muscat-tour-half-day/3.avif",
      ],
      perks: ["Flexible duration", "Small group", "Hotel pickup"],
      highlights: [
        "Half-day to multi-day options",
        "Small group experience",
        "Flexible itinerary",
      ],
      included: ["Transportation", "Guide", "Hotel pickup"],
      essentials: ["Comfortable clothing", "Camera", "Water"],
      overview: "A flexible half-day to multi-day tour of Muscat with small group.",
      rating: 4.8,
      reviews: 25,
      badge: "Flexible",
      location: "Muscat, Oman",
      meetingPoint: "Hotel pickup within Muscat",
    },
    {
      id: "muscat-desert-wadi-bani-khalid-quad-bike",
      title: "Muscat: Desert & Wadi Bani Khalid Tour with Quad Bike Option",
      description: "Desert and Wadi Bani Khalid tour with optional quad bike adventure.",
      duration: "9 - 10 hours • Pickup available",
      price: 13323,
      currency: "INR",
      image: "/assets/categories/car-rental/muscat-desert-wadi-bani-khalid-quad-bike/1.avif",
      gallery: [
        "/assets/categories/car-rental/muscat-desert-wadi-bani-khalid-quad-bike/2.avif",
        "/assets/categories/car-rental/muscat-desert-wadi-bani-khalid-quad-bike/3.avif",
      ],
      perks: ["Desert tour", "Quad bike option", "Wadi visit"],
      highlights: [
        "Explore desert dunes",
        "Optional quad bike adventure",
        "Visit Wadi Bani Khalid",
      ],
      included: ["Transportation", "Guide", "Quad bike option", "Hotel pickup"],
      essentials: ["Comfortable clothing", "Sun protection", "Adventure spirit"],
      overview: "A desert and Wadi Bani Khalid tour with optional quad bike adventure.",
      rating: 4.8,
      reviews: 16,
      badge: "Adventure",
      location: "Muscat, Oman",
      meetingPoint: "Hotel pickup within Muscat",
    },
    {
      id: "muscat-guided-overnight-desert-camp",
      title: "From Muscat: Guided Overnight Desert Camp Tour",
      description: "Guided overnight desert camp tour from Muscat.",
      duration: "2 - 3 days • Small group • Pickup available",
      price: 51665,
      currency: "INR",
      image: "/assets/categories/car-rental/muscat-guided-overnight-desert-camp/1.avif",
      gallery: [
        "/assets/categories/car-rental/muscat-guided-overnight-desert-camp/2.webp",
        "/assets/categories/car-rental/muscat-guided-overnight-desert-camp/3.webp",
      ],
      perks: ["Overnight camp", "Multi-day tour", "Desert experience"],
      highlights: [
        "Overnight desert camping",
        "2-3 days adventure",
        "Desert experience",
      ],
      included: ["Accommodation", "Meals", "Transportation", "Guide"],
      essentials: ["Camping gear", "Warm clothing", "Personal items"],
      overview: "A guided overnight desert camp tour from Muscat with 2-3 days duration.",
      rating: 4.9,
      reviews: 14,
      badge: "Overnight",
      location: "Muscat, Oman",
      meetingPoint: "Hotel pickup within Muscat",
    },
    {
      id: "muscat-full-day-private-city-tour-luxury",
      title: "Muscat: Full-Day Private City Tour by luxury Car with Guide",
      description: "Full-day private city tour by luxury car with professional guide.",
      duration: "1 day • Skip the line • Small group",
      price: 10658,
      currency: "INR",
      image: "/assets/categories/car-rental/muscat-full-day-private-city-tour-luxury/1.avif",
      gallery: [
        "/assets/categories/car-rental/muscat-full-day-private-city-tour-luxury/2.webp",
        "/assets/categories/car-rental/muscat-full-day-private-city-tour-luxury/3.avif",
      ],
      perks: ["Luxury car", "Private tour", "Full day"],
      highlights: [
        "Luxury vehicle",
        "Private guide",
        "Full-day exploration",
      ],
      included: ["Luxury vehicle", "Professional guide", "Full-day service"],
      essentials: ["Modest clothing", "Comfortable shoes", "Camera"],
      overview: "A full-day private city tour by luxury car with professional guide.",
      rating: 5.0,
      reviews: 4,
      badge: "Luxury",
      location: "Muscat, Oman",
      meetingPoint: "Hotel pickup within Muscat",
    },
    {
      id: "muscat-coastal-sunset-boat-trip",
      title: "Muscat : Coastal & Sunset Boat Trip",
      description: "Coastal and sunset boat trip along Muscat's beautiful coastline.",
      duration: "1 hour",
      price: 3464,
      currency: "INR",
      image: "/assets/categories/car-rental/muscat-coastal-sunset-boat-trip/1.webp",
      gallery: [
        "/assets/categories/car-rental/muscat-coastal-sunset-boat-trip/2.webp",
        "/assets/categories/car-rental/muscat-coastal-sunset-boat-trip/3.avif",
      ],
      perks: ["Boat trip", "Sunset views", "Coastal scenery"],
      highlights: [
        "Coastal boat ride",
        "Sunset views",
        "Beautiful scenery",
      ],
      included: ["Boat trip", "Guide", "Safety equipment"],
      essentials: ["Comfortable clothing", "Camera", "Sun protection"],
      overview: "A scenic coastal and sunset boat trip along Muscat's beautiful coastline.",
      rating: 4.0,
      reviews: 4,
      badge: "Boat trip",
      location: "Muscat, Oman",
      meetingPoint: "Marina pickup point, Muscat",
    },
  ],
  "airport-transport": [
    {
      id: "muscat-airport-all-city-hotels-private-transfers",
      title: "Muscat Airport to all city Hotels drop: Private Transfers",
      description: "Private transfer service from Muscat Airport to all city hotels.",
      duration: "30 minutes • Private group • Pickup available",
      price: 1776,
      currency: "INR",
      image: "/assets/categories/airport-transport/muscat-airport-all-city-hotels-private-transfers/1.avif",
      gallery: [
        "/assets/categories/airport-transport/muscat-airport-all-city-hotels-private-transfers/2.avif",
        "/assets/categories/airport-transport/muscat-airport-all-city-hotels-private-transfers/3.avif",
      ],
      perks: ["Private group", "Hotel drop-off", "Airport pickup"],
      highlights: [
        "Private transfer from airport",
        "Drop-off at any city hotel",
        "Professional driver",
      ],
      included: ["Private vehicle", "Professional driver", "Airport pickup"],
      essentials: ["Flight details required", "Valid ID", "Comfortable travel"],
      overview: "Private transfer service from Muscat Airport to all city hotels with professional driver.",
      rating: 4.8,
      reviews: 62,
      badge: "Top pick",
      location: "Muscat, Oman",
      meetingPoint: "Muscat Airport arrivals",
    },
    {
      id: "muscat-airport-private-transfer-all-hotels",
      title: "Muscat: Airport Private Transfer to/from all Muscat Hotels",
      description: "Private airport transfer service to and from all Muscat hotels.",
      duration: "25 - 30 minutes • Private group • Pickup available",
      price: 2132,
      currency: "INR",
      image: "/assets/categories/airport-transport/muscat-airport-private-transfer-all-hotels/1.webp",
      gallery: [
        "/assets/categories/airport-transport/muscat-airport-private-transfer-all-hotels/2.avif",
        "/assets/categories/airport-transport/muscat-airport-private-transfer-all-hotels/3.avif",
      ],
      perks: ["Private group", "All hotels", "Round trip available"],
      highlights: [
        "Transfer to/from all Muscat hotels",
        "Private vehicle and driver",
        "Flexible scheduling",
      ],
      included: ["Private vehicle", "Professional driver", "Hotel pickup/drop-off"],
      essentials: ["Flight details", "Hotel information", "Valid ID"],
      overview: "Private airport transfer service to and from all Muscat hotels with professional driver.",
      rating: 4.7,
      reviews: 120,
      badge: "Top rated",
      location: "Muscat, Oman",
      meetingPoint: "Muscat Airport or hotel",
    },
    {
      id: "luxury-muscat-airport-pickup-dropoff",
      title: "Luxury Muscat airport pickup and drop off",
      description: "Luxury airport pickup and drop-off service in Muscat.",
      duration: "30 minutes • Skip the line • Private group",
      price: 8882,
      currency: "INR",
      image: "/assets/categories/airport-transport/luxury-muscat-airport-pickup-dropoff/1.webp",
      gallery: [
        "/assets/categories/airport-transport/luxury-muscat-airport-pickup-dropoff/2.webp",
        "/assets/categories/airport-transport/luxury-muscat-airport-pickup-dropoff/3.webp",
      ],
      perks: ["Luxury vehicle", "Skip the line", "Private group"],
      highlights: [
        "Luxury vehicle service",
        "Skip the line access",
        "Premium experience",
      ],
      included: ["Luxury vehicle", "Professional chauffeur", "Airport service"],
      essentials: ["Flight details", "Valid ID", "Luxury travel"],
      overview: "Luxury airport pickup and drop-off service in Muscat with premium vehicles.",
      rating: 5.0,
      reviews: 2,
      badge: "Luxury",
      location: "Muscat, Oman",
      meetingPoint: "Muscat Airport",
    },
    {
      id: "muscat-private-airport-transfer-any-hotel",
      title: "Muscat: Private Airport Transfer to/from any Muscat Hotel",
      description: "Private airport transfer service to and from any Muscat hotel.",
      duration: "25 minutes • Skip the line • Private group",
      price: 2043,
      currency: "INR",
      image: "/assets/categories/airport-transport/muscat-private-airport-transfer-any-hotel/1.webp",
      gallery: [
        "/assets/categories/airport-transport/muscat-private-airport-transfer-any-hotel/2.webp",
        "/assets/categories/airport-transport/muscat-private-airport-transfer-any-hotel/3.webp",
      ],
      perks: ["Any hotel", "Skip the line", "Private group"],
      highlights: [
        "Transfer to/from any hotel",
        "Skip the line service",
        "Private vehicle",
      ],
      included: ["Private vehicle", "Professional driver", "Hotel service"],
      essentials: ["Flight details", "Hotel information", "Valid ID"],
      overview: "Private airport transfer service to and from any Muscat hotel with skip the line access.",
      rating: 4.5,
      reviews: 23,
      badge: "Private",
      location: "Muscat, Oman",
      meetingPoint: "Muscat Airport or hotel",
    },
    {
      id: "muscat-taxi-private-luxury-transfer-airport",
      title: "Muscat : Taxi Private luxury transfer from Airport",
      description: "Private luxury taxi transfer service from Muscat Airport.",
      duration: "1 day • Skip the line • Private group",
      price: 4133,
      currency: "INR",
      image: "/assets/categories/airport-transport/muscat-taxi-private-luxury-transfer-airport/1.webp",
      gallery: [
        "/assets/categories/airport-transport/muscat-taxi-private-luxury-transfer-airport/2.avif",
        "/assets/categories/airport-transport/muscat-taxi-private-luxury-transfer-airport/3.webp",
      ],
      perks: ["Luxury taxi", "Skip the line", "Private group"],
      highlights: [
        "Luxury taxi service",
        "Private transfer",
        "Comfortable vehicle",
      ],
      included: ["Luxury taxi", "Professional driver", "Airport pickup"],
      essentials: ["Flight details", "Valid ID", "Comfortable travel"],
      overview: "Private luxury taxi transfer service from Muscat Airport with professional driver.",
      rating: 4.5,
      reviews: 13,
      badge: "Luxury",
      location: "Muscat, Oman",
      meetingPoint: "Muscat Airport",
    },
    {
      id: "best-muscat-airport-transfer-airport",
      title: "The Best Muscat Airport Transfer",
      description: "Premium airport transfer service in Muscat with professional driver.",
      duration: "45 minutes",
      price: 3997,
      currency: "INR",
      image: "/assets/categories/airport-transport/best-muscat-airport-transfer-airport/1.avif",
      gallery: [
        "/assets/categories/airport-transport/best-muscat-airport-transfer-airport/2.webp",
        "/assets/categories/airport-transport/best-muscat-airport-transfer-airport/3.avif",
      ],
      perks: ["Airport transfer", "Professional driver", "Comfortable vehicle"],
      highlights: [
        "Meet and greet service",
        "Comfortable vehicle for up to 4 passengers",
        "Luggage assistance",
      ],
      included: ["Private vehicle", "Professional driver", "Airport pickup"],
      essentials: ["Flight details", "Valid ID", "Comfortable travel"],
      overview: "The best airport transfer service in Muscat with professional driver.",
      rating: 5.0,
      reviews: 3,
      badge: "Airport transfer",
      location: "Muscat, Oman",
      meetingPoint: "Muscat Airport",
    },
    {
      id: "muscat-airport-transfer-mct-city-center",
      title: "Muscat: Airport Transfer from MCT to Muscat City Center",
      description: "Airport transfer service from MCT to Muscat City Center.",
      duration: "1 hour • Private group",
      price: 4352,
      currency: "INR",
      image: "/assets/categories/airport-transport/muscat-airport-transfer-mct-city-center/1.avif",
      gallery: [
        "/assets/categories/airport-transport/muscat-airport-transfer-mct-city-center/2.avif",
        "/assets/categories/airport-transport/muscat-airport-transfer-mct-city-center/3.avif",
      ],
      perks: ["City center transfer", "Private group", "Professional driver"],
      highlights: [
        "Transfer from MCT airport",
        "Drop-off at city center",
        "Comfortable vehicle for up to 2 passengers",
      ],
      included: ["Private vehicle", "Professional driver", "Airport pickup"],
      essentials: ["Flight details", "Valid ID", "City center destination"],
      overview: "Airport transfer service from MCT to Muscat City Center with professional driver.",
      rating: 5.0,
      reviews: 3,
      badge: "City transfer",
      location: "Muscat, Oman",
      meetingPoint: "MCT Airport arrivals",
    },
    {
      id: "oman-airport-pickup-dropoff",
      title: "Oman Airport Pick up and Drop off",
      description: "Airport pickup and drop-off service in Oman.",
      duration: "5 minutes • Pickup available",
      price: 8266,
      currency: "INR",
      image: "/assets/categories/airport-transport/oman-airport-pickup-dropoff/1.avif",
      gallery: [
        "/assets/categories/airport-transport/oman-airport-pickup-dropoff/2.avif",
        "/assets/categories/airport-transport/oman-airport-pickup-dropoff/3.avif",
      ],
      perks: ["Pickup and drop-off", "Quick service", "Professional driver"],
      highlights: [
        "Quick airport service",
        "Pickup and drop-off",
        "Comfortable vehicle for up to 4 passengers",
      ],
      included: ["Private vehicle", "Professional driver", "Airport service"],
      essentials: ["Flight details", "Valid ID", "Quick service"],
      overview: "Airport pickup and drop-off service in Oman with quick and efficient service.",
      rating: 5.0,
      reviews: 3,
      badge: "Quick service",
      location: "Muscat, Oman",
      meetingPoint: "Oman Airport",
    },
    {
      id: "muscat-full-day-car-driver-hire-airport",
      title: "Muscat: Full-Day Car and Driver Hire in Muscat CityTerritory",
      description: "Full-day car and driver hire service in Muscat city territory.",
      duration: "9 hours • Skip the line • Private group",
      price: 23537,
      currency: "INR",
      image: "/assets/categories/airport-transport/muscat-full-day-car-driver-hire-airport/1.webp",
      gallery: [
        "/assets/categories/airport-transport/muscat-full-day-car-driver-hire-airport/2.webp",
        "/assets/categories/airport-transport/muscat-full-day-car-driver-hire-airport/3.avif",
      ],
      perks: ["Full day", "Private group", "Professional driver"],
      highlights: [
        "Full-day service",
        "Private vehicle and driver",
        "Flexible itinerary",
      ],
      included: ["Vehicle with driver", "9 hours service", "Hotel pickup"],
      essentials: ["Valid ID", "Comfortable clothing", "Camera"],
      overview: "Full-day car and driver hire service for exploring Muscat city territory.",
      rating: 4.3,
      reviews: 4,
      badge: "Full day",
      location: "Muscat, Oman",
      meetingPoint: "Hotel pickup within Muscat",
    },
    {
      id: "muscat-private-transfer-jabal-akhdar-alila",
      title: "Muscat: Private transfer to/from Jabal Akhdar-Alila Hotel",
      description: "Private transfer service to and from Jabal Akhdar-Alila Hotel.",
      duration: "2 hours • Skip the line • Private group",
      price: 10658,
      currency: "INR",
      image: "/assets/categories/airport-transport/muscat-private-transfer-jabal-akhdar-alila/1.avif",
      gallery: [
        "/assets/categories/airport-transport/muscat-private-transfer-jabal-akhdar-alila/2.avif",
        "/assets/categories/airport-transport/muscat-private-transfer-jabal-akhdar-alila/3.avif",
      ],
      perks: ["Jabal Akhdar transfer", "Skip the line", "Private group"],
      highlights: [
        "Transfer to/from Jabal Akhdar",
        "Alila Hotel service",
        "Mountain route",
      ],
      included: ["Private vehicle", "Professional driver", "Hotel transfer"],
      essentials: ["Hotel booking", "Valid ID", "Mountain travel"],
      overview: "Private transfer service to and from Jabal Akhdar-Alila Hotel with professional driver.",
      rating: 5.0,
      reviews: 7,
      badge: "Mountain transfer",
      location: "Muscat, Oman",
      meetingPoint: "Muscat or Alila Hotel",
    },
    {
      id: "best-private-transfer-muscat-airport-airport",
      title: "Best Private Transfer From Muscat Airport",
      description: "Premium private transfer service from Muscat Airport with professional driver.",
      duration: "40 minutes • Private group • Pickup available",
      price: 4885,
      currency: "INR",
      image: "/assets/categories/airport-transport/best-private-transfer-muscat-airport-airport/1.webp",
      gallery: [
        "/assets/categories/airport-transport/best-private-transfer-muscat-airport-airport/2.avif",
        "/assets/categories/airport-transport/best-private-transfer-muscat-airport-airport/3.avif",
      ],
      perks: ["Private group", "Airport pickup", "Professional driver"],
      highlights: [
        "Meet and greet at airport",
        "Comfortable vehicle for up to 7 passengers",
        "Luggage assistance",
      ],
      included: ["Private vehicle", "Professional driver", "Airport pickup"],
      essentials: ["Flight details required", "Valid ID", "Comfortable travel"],
      overview: "Premium private transfer service from Muscat Airport to your destination.",
      rating: 4.3,
      reviews: 0,
      badge: "Airport transfer",
      location: "Muscat, Oman",
      meetingPoint: "Muscat Airport arrivals",
    },
    {
      id: "muscat-private-transfer-jabel-akhdar-alila-resort",
      title: "Muscat: Private Transfer to/from Jabel Akhdar & Alila Resort",
      description: "Private transfer service to and from Jabel Akhdar and Alila Resort.",
      duration: "2 hours • Skip the line • Private group",
      price: 12435,
      currency: "INR",
      image: "/assets/categories/airport-transport/muscat-private-transfer-jabel-akhdar-alila-resort/1.webp",
      gallery: [
        "/assets/categories/airport-transport/muscat-private-transfer-jabel-akhdar-alila-resort/2.avif",
        "/assets/categories/airport-transport/muscat-private-transfer-jabel-akhdar-alila-resort/3.webp",
      ],
      perks: ["Jabel Akhdar transfer", "Alila Resort", "Skip the line"],
      highlights: [
        "Transfer to/from Jabel Akhdar",
        "Alila Resort service",
        "Mountain route experience",
      ],
      included: ["Private vehicle", "Professional driver", "Resort transfer"],
      essentials: ["Resort booking", "Valid ID", "Mountain travel"],
      overview: "Private transfer service to and from Jabel Akhdar and Alila Resort with professional driver.",
      rating: 5.0,
      reviews: 10,
      badge: "Resort transfer",
      location: "Muscat, Oman",
      meetingPoint: "Muscat or Alila Resort",
    },
    {
      id: "muscat-private-transfer-airport-city-hotels",
      title: "Muscat: Private Transfer from Airport to Muscat City Hotels",
      description: "Private transfer service from airport to Muscat city hotels.",
      duration: "1 hour • Private group • Pickup available",
      price: 5329,
      currency: "INR",
      image: "/assets/categories/airport-transport/muscat-private-transfer-airport-city-hotels/1.avif",
      gallery: [
        "/assets/categories/airport-transport/muscat-private-transfer-airport-city-hotels/2.avif",
        "/assets/categories/airport-transport/muscat-private-transfer-airport-city-hotels/3.webp",
      ],
      perks: ["City hotels", "Private group", "Airport pickup"],
      highlights: [
        "Transfer to city hotels",
        "Comfortable vehicle for up to 3 passengers",
        "Professional driver",
      ],
      included: ["Private vehicle", "Professional driver", "Airport pickup"],
      essentials: ["Flight details", "Hotel information", "Valid ID"],
      overview: "Private transfer service from airport to Muscat city hotels with professional driver.",
      rating: 4.3,
      reviews: 10,
      badge: "City hotels",
      location: "Muscat, Oman",
      meetingPoint: "Muscat Airport",
    },
    {
      id: "muscat-airport-transfer-simple",
      title: "Muscat Airport Transfer",
      description: "Simple and reliable airport transfer service in Muscat.",
      duration: "30 minutes • Private group",
      price: 4441,
      currency: "INR",
      image: "/assets/categories/airport-transport/muscat-airport-transfer-simple/1.webp",
      gallery: [
        "/assets/categories/airport-transport/muscat-airport-transfer-simple/2.avif",
        "/assets/categories/airport-transport/muscat-airport-transfer-simple/3.avif",
      ],
      perks: ["Airport transfer", "Private group", "Reliable service"],
      highlights: [
        "Simple airport transfer",
        "Comfortable vehicle for up to 3 passengers",
        "Professional driver",
      ],
      included: ["Private vehicle", "Professional driver", "Airport service"],
      essentials: ["Flight details", "Valid ID", "Comfortable travel"],
      overview: "Simple and reliable airport transfer service in Muscat with professional driver.",
      rating: 4.8,
      reviews: 0,
      badge: "Reliable",
      location: "Muscat, Oman",
      meetingPoint: "Muscat Airport",
    },
    {
      id: "private-transfer-muscat-airport-jebel-akhdar-shams",
      title: "Private Transfer: Muscat or Airport to Jebel Akhdar/Shams",
      description: "Private transfer service from Muscat or Airport to Jebel Akhdar/Shams.",
      duration: "2 hours • Private group • Pickup available",
      price: 22205,
      currency: "INR",
      image: "/assets/categories/airport-transport/private-transfer-muscat-airport-jebel-akhdar-shams/1.avif",
      gallery: [
        "/assets/categories/airport-transport/private-transfer-muscat-airport-jebel-akhdar-shams/2.avif",
        "/assets/categories/airport-transport/private-transfer-muscat-airport-jebel-akhdar-shams/3.avif",
      ],
      perks: ["Jebel Akhdar transfer", "Mountain route", "Private group"],
      highlights: [
        "Transfer to Jebel Akhdar/Shams",
        "Mountain route experience",
        "Comfortable vehicle for up to 4 passengers",
      ],
      included: ["Private vehicle", "Professional driver", "Mountain transfer"],
      essentials: ["Valid ID", "Mountain travel", "Comfortable clothing"],
      overview: "Private transfer service from Muscat or Airport to Jebel Akhdar/Shams with professional driver.",
      rating: 5.0,
      reviews: 0,
      badge: "Mountain transfer",
      location: "Muscat, Oman",
      meetingPoint: "Muscat or Airport",
    },
    {
      id: "muscat-airport-transfer-mussanah-al-nahda",
      title: "Muscat Airport Transfer to Mussanah or Al Nahda Area Hotels",
      description: "Airport transfer service to Mussanah or Al Nahda area hotels.",
      duration: "2.5 hours • Private group • Pickup available",
      price: 12701,
      currency: "INR",
      image: "/assets/categories/airport-transport/muscat-airport-transfer-mussanah-al-nahda/1.webp",
      gallery: [
        "/assets/categories/airport-transport/muscat-airport-transfer-mussanah-al-nahda/2.avif",
        "/assets/categories/airport-transport/muscat-airport-transfer-mussanah-al-nahda/3.avif",
      ],
      perks: ["Mussanah transfer", "Al Nahda area", "Private group"],
      highlights: [
        "Transfer to Mussanah area",
        "Al Nahda area hotels",
        "Comfortable vehicle for up to 3 passengers",
      ],
      included: ["Private vehicle", "Professional driver", "Area transfer"],
      essentials: ["Flight details", "Hotel information", "Valid ID"],
      overview: "Airport transfer service to Mussanah or Al Nahda area hotels with professional driver.",
      rating: 4.0,
      reviews: 0,
      badge: "Area transfer",
      location: "Muscat, Oman",
      meetingPoint: "Muscat Airport",
    },
  ],
  "hotel-booking": [],
};

